### ISSUE TITLE
Vite controller is now useless

### ISSUE THREAD

**Issue by Vincz** [lhapaipai/vite-bundle#12]
The goal of the vite controller is to proxy assets calls to the dev server.  
It is not necessary anymore as vite offer an option to change the path of assets.

Configuration example:

```js
export default defineConfig({
    ...
    server: {
        origin: 'https://localhost:3000',
        ...
    }
```

With this configuration, in development, the assets will be serve with the correct path.

**Comment by lhapaipai** [comment]
Hi @Vincz,
Thanks for your issue. I've modified [lhapaipai/vite-plugin-symfony](https://github.com/lhapaipai/vite-plugin-symfony) so that it defines the origin that you suggested if this one has not yet been defined.

for the Vite Controller I left it because it still allows to relay the ping. Is it still necessary?
