### ISSUE TITLE
Loading Build assets when in dev mode

### ISSUE THREAD

**Issue by sander-lameco** [lhapaipai/vite-bundle#37]
We are wondering since our backend-developers don't make changes to the JS and SCSS and thus don't really need to do a `yarn dev` if it is possible to rewrite the config to not load assets from `localhost:3000` but directly from the generated (via `yarn build`) assets. 

Not sure if this is a config we have to make in the `config/packages/pentatrion_vite.yaml` or the `vite.config.js`.

**Comment by lhapaipai** [comment]
hi @sander-lameco, I'm not sure to fully understand your issue.
actually all assets imported via js with an import are processed by vite and copied into the `/public/build/assets/` directory. a listing of all your assets is available in `/public/build/manifest.json` and with vite@v3 and vite-plugin-symfony@<0.7.2 in `/public/build/entrypoints.json`.
only this files  can be accessed to your backend-developers with the symfony asset component and the `asset` twig function via `ViteAssetVersionStrategy`. read the doc for the implementation https://github.com/lhapaipai/vite-bundle#symfony-asset-component.
I'm not sure I'm answered your question but feel free to ask if you want some clarification.

**Comment by sander-lameco** [comment]
Sorry maybe this can make it a bit more clear:

`npm / yarn dev` starts `vite` and keeps it  running in the background to serve the assets (SCSS/JS) via `localhost:port` when running the project in `dev` mode.

`npm / yarn build` start the `vite build` process but the build assets only load while the project is in `production` mode.

Is there a way to do a `vite build` and load those assets while the project is in `dev` mode.

**Comment by hdasdoria** [comment]
@sander-lameco are you calling your assets with `{{ vite_entry_link_tags() }}` and `{{ vite_entry_script_tags() }}` in your twig? If you do so, this bundle automatically include the assets with the right URLs.

It could also be because when you push your files to your backend developers, you are not sending them the built version of your assets.
The correct way to work is to run `yarn dev` during your development, but once you commit your files to git, you should run a `yarn build` before. So the `manifest.json` and the `entrypoints.json` are in a build mode, and not in a dev mode.

Your asset's version on your git repository should always be the built one.

**Comment by lhapaipai** [comment]
I'm sorry @sander-lameco, but I really doesn't understand your issue. to tell you the truth when you were talking about `assets` I was thinking of .jpg/.png files. That's why I talk you about `ViteAssetVersionStrategy`.

can you write precisely the steps to follow from scratch to reproduce your issue.

**Comment by sander-lameco** [comment]
Hi @lhapaipai checked with my colleague which told me it now works as intended. Somehow we were still using v1.2.0 and recently updated to v2.3.*. Sorry for any disturbance.
