### ISSUE TITLE
Lazy loading of Stimulus controllers is different from stimulus-bridge

### ISSUE THREAD

**Issue by YummYume** [lhapaipai/vite-bundle#87]
### vite-bundle version

6.4.4

### vite-plugin-symfony version

6.4.3

### your OS, Symfony version, PHP version, Node version

Linux, Symfony 7.0.6, PHP 8.3.6, Node 20.11.0

### Description

Hello, first off, thanks a lot for making this bundle :pray: It's incredible.

While migrating multiple apps from Webpack Encore to this bundle, I noticed that the lazy-loading of Stimulus controllers was not working the same way as when using [stimulus-bridge](https://github.com/symfony/stimulus-bridge).

The excepted behaviour was to only load controllers when they're actually used on the page. This is what was achieved using stimulus-bridge and, as the doc claims, "By default all your controllers are lazy loaded.". However, the lazy-loading of Vite still loads all the controllers, even when they're not actually used.

This isn't a problem for small apps, but for medium to large sized apps, or apps using external bundles, it can be quite troublesome to load so many controllers (and have so many http requests) on a page that would only use one or two controllers at most.

Is this the intended behaviour of this bundle ? Or am I missing something ?

### How to reproduce

Add a few controllers in `assets/controllers` for example.

```ts
// assets/bootstrap.js
const app = startStimulusApp();

registerControllers(
  app,
  import.meta.glob('./controllers/*_(lazy)\?controller.[jt]s(x)\?') 
)
```

Then go to a page where you don't use any controllers and inspect the network. All the controller files are still being loaded.

### Possible Solution

Check the [stimulus-bridge implementation](https://github.com/symfony/stimulus-bridge/blob/main/src/webpack/generate-lazy-controller.ts).

What happens here is that controllers marked as "lazy" are not actually registered, but being proxied by a `generate-lazy-controller`, which checks if any lazy loaded controller is present in the application, and only then loads them.

**Comment by YummYume** [comment]
After investigating a bit, and looking at the source code, it seems that only controllers ending with `lazycontroller.*` will get properly registered as "lazy". The documentation about this is very confusing and led me to think that they would all be lazy-loaded by default unless I defined `eager: true` in the glob options.

I ended up making a function to change the name of my controllers to satisfy this constraint, like so :

```ts
const transformImportsToLazy = (imports: Record<string, () => Promise<unknown>>) => {
  const lazyImports: Record<string, () => Promise<unknown>> = {};

  for (const [key, value] of Object.entries(imports)) {
    if (key.match(/_controller\.(ts|js)$/)) {
      lazyImports[key.replace(/_controller\.(ts|js)$/, '_lazycontroller.$1')] = value;
    } else {
      lazyImports[key] = value;
    }
  }

  return lazyImports;
};
```

Maybe the documentation could be updated to better explain this part ?

**Comment by papppeter** [comment]
did you checked that comments aren't removed at building time? I had before a tsconfig which did removed them.

**Comment by lhapaipai** [comment]
I @YummYume,
 indeed there are some differences between the 2 implementations due to the fact that webpack uses `commonjs` and quickly the `es modules`

the glob import is lazy by default : https://vitejs.dev/guide/features#glob-import

here is the current behavior

```ts
const modules = import.meta.glob('...', { eager: true })
/*
modules === {
  "./controllers/notifier_controller.js": {
    default: <your-stimulus-controller>
  },
  // ...
}
*/
const lazyModules = import.meta.glob('...');
/*
modules === {
  "./controllers/notifier_controller.js": () => Promise.resolve({
    default: <your-stimulus-controller>
  }),
  // ...
}
*/
```

if you do an import with `import.meta.glob('....', { eager: true })` when you call `registerControllers` your files are already loaded, it is too late to have lazy behavior.
So in this case, **at build time, your entry point and all your controllers will be compiled into a single file**.

on the other hand if you do an import with `import.meta.glob('....')` when you call `registerControllers` your files are not yet loaded.
So in this case, **at build time, your entry point and all your controllers will be compiled into separate files**.
However, at this time we still have not decided on the behavior to follow when calling the `registerControllers` function.

The behavior will be dictated by the file name suffix. if it ends with:

- `_controller.[jt]s(x)`: the function is called, the promise is resolved and we will have an operation similar to the `eager` behavior. The import is resolved when the script is executed
- `_lazycontroller.[jt]s(x)`: our controller is wrapped in a [lazyController](https://github.com/lhapaipai/symfony-vite-dev/blob/ef656db6eaf49d50fcdda62d131a55ec9a307724/src/vite-plugin-symfony/src/stimulus/helpers/base.ts#L12) which will only resolve the promise when the controller is mounted the first time. The import is only resolved when a DOM element is present for the first time which requests to load the controller.


actually the doc is incorrect compared to my explanation... Before updating it can you give me your opinion. Do you achieve the desired behavior with my explanations? Do you have any suggestions? Could you explain to me in more detail in what context you use your `transformImportsToLazy` function described above?



```ts
// https://github.com/lhapaipai/symfony-vite-dev/blob/ef656db6eaf49d50fcdda62d131a55ec9a307724/src/vite-plugin-symfony/src/stimulus/helpers/base.ts#L49

type LazyModule<M> = () => Promise<M>;
type ImportedModule<M> = M | LazyModule<M>;
type ImportedModules<M> = Record<string, ImportedModule<M>>;

export function registerControllers(app: Application, modules: ImportedModules<ControllerModule>) {
  Object.entries(modules).forEach(([filePath, importedModule]) => {
    const { identifier, lazy } = getStimulusControllerFileInfos(filePath);
    if (!identifier) {
      throw new Error(`Invalid filePath name ${filePath}`);
    }

    
    if (typeof importedModule === "function") {
      // modules loaded with import.meta.glob('....', { eager: false })
      if (lazy) {
        app.register(identifier, getLazyController(importedModule));
      } else {
        importedModule().then((controllerConstructor) => {
          if (identifier && typeof controllerConstructor.default === "function") {
            app.register(identifier, controllerConstructor.default);
          }
        });
      }
    } else {
      // modules loaded with import.meta.glob('....', { eager: true })
      app.register(identifier, importedModule.default);
    }
  });
}
```

good afternoon

**Comment by YummYume** [comment]
Hi @lhapaipai, thanks for such a detailed answer !

Back when we were using Webpack Encore, all our controller files ended with `_controller.{ts,js}`. We had to register multiple controller directories coming from different places, where most of the controllers had the magic comment `/* stimulusFetch: 'lazy' */` on them.

However, sometimes, we needed some controllers to **not** be lazy-loaded, depending on the app. Because, for example, some controllers needed to be connected as soon as possible to listen to events, or be registered as outlets. In this case, we would manually register the controller again, but without the lazy-loading behaviour. Here's how it looked like :

```ts
import { definitionsFromContext } from '@hotwired/stimulus-webpack-helpers';
import { startStimulusApp } from '@symfony/stimulus-bridge';
import XController from './controllers/x_controller';

export const app = startStimulusApp(
  require.context('@symfony/stimulus-bridge/lazy-controller-loader!./controllers', true, /\.[jt]sx?$/),
);

app.load(
  definitionsFromContext(
    require.context('@symfony/stimulus-bridge/lazy-controller-loader!$first-alias/controllers', true, /\.[jt]sx?$/),
  ),
);

app.load(
  definitionsFromContext(
    require.context('@symfony/stimulus-bridge/lazy-controller-loader!$second-alias/controllers', true, /\.[jt]sx?$/),
  ),
);

// This controller has already been registered, but we need it non-lazy for this app
app.register('x-controller', XController);
```

Now, after migrating to Vite, the controllers would be lazy-loaded as you stated above, but they wouldn't be wrapped in the special lazy controller. This was because they were all ending with `_controller.{ts,js}` and not `_lazycontroller.{ts,js}`, which is why I created this `transformImportsToLazy` function to fake their real name to get the real lazy-loading behaviour. Here's the full implementation :

```ts
export const transformImportsToLazy = (
  imports: Record<string, () => Promise<unknown>>,
  exclude: string[] = [],
  controllerMatch = /_controller\.(ts|js)$/,
) => {
  const lazyImports: Record<string, () => Promise<unknown>> = {};

  for (const [key, value] of Object.entries(imports)) {
    if (key.match(controllerMatch) && !exclude.includes(key)) {
      lazyImports[key.replace(controllerMatch, '_lazycontroller.$1')] = value;
    } else {
      lazyImports[key] = value;
    }
  }

  return lazyImports;
};
```

And here's how the app looks like with Vite currently :

```ts
import { registerControllers, startStimulusApp } from 'vite-plugin-symfony/stimulus/helpers';

import { transformImportsToLazy } from './vite';

export const app = startStimulusApp();

app.debug = import.meta.env.MODE === 'development';

registerControllers(
  app,
  // @ts-expect-error - controllers are lazy loaded
  transformImportsToLazy(import.meta.glob('./controllers/**/*_(lazy)?controller.[jt]s(x)?'), [
    // This controller should not be lazy-loaded afterall, so we do not convert its name
    './controllers/x_controller.ts',
  ]),
);

registerControllers(
  app,
  // @ts-expect-error - controllers are lazy loaded
  transformImportsToLazy(import.meta.glob('$first-alias/controllers/**/*_(lazy)?controller.[jt]s(x)?')),
);

registerControllers(
  app,
  // @ts-expect-error - controllers are lazy loaded
  transformImportsToLazy(import.meta.glob('$second-alias/controllers/**/*_(lazy)?controller.[jt]s(x)?')),
);
```

Notice the `@ts-expect-error`, because the typing seems to be wrong and only accept eager imports (without a Promise).

Now, this implementation works fine, but is merely a workaround. Having to manually set the names of the controllers we do not want to have lazy loaded is also not ideal (if they change name, etc...). And excluding their name from the glob would quickly create a messy, hard to read string.

I think the solution could be one of many, but the most important would probably be to either not use the name to match "lazy" controllers, or at least give control for the logic used. It could also be convenient if controllers could directly declare their default behaviour (lazy or not) inside their file directly. It could make the migration from Webpack to Vite easier for larger apps. But I don't know how hard that would be to implement. What do you think ?

**Comment by lhapaipai** [comment]
hi @YummYume,
sorry for this long time ...

I'm coming back to you because I'm looking to improve all this.

There are many new features pending for the bundle that require a major version change and so I would like to take the opportunity to include breaking changes with stimulus.

but we both agree that the implementation is not exactly beautiful.

in fact I agree with you about implementing lazy controllers directly in the files.

and there is a second thing that doesn't suit me, it's the name of the controller that is deduced from the name of the file. I find that not very portable. we can't put controllers in directories without having a long name. if the file name is too long we also have an id too long, no camelcase management...

Here are some ideas

```ts
// ./can-be-located-anywhere because he has 'stimulusControllerId'
import { Controller } from "@hotwired/stimulus";

/* stimulusFetch: 'lazy' */
/* stimulusControllerId: 'cropper' */
export default class extends Controller {
  // ...
}
```

```ts
// ./assets/controllers/cropper_controller.ts
import { Controller } from "@hotwired/stimulus";

// stimulusControllerId is absent the id is deducted from "cropper_controller" like before.

/* stimulusFetch: 'lazy' */
export default class extends Controller {
  // ...
}
```

```ts
// ./assets/controllers/cropper_controller.ts
import { Controller } from "@hotwired/stimulus";

// stimulusControllerId is absent the id is deducted from "cropper_controller" like before.
// stimulusFetch is absent the controller is loaded eagerly

export default class extends Controller {
  // ...
}
```

```ts
import {
  startStimulusApp,
  registerControllers,
  registerController,
} from "vite-plugin-symfony/stimulus/helpers";
const app = startStimulusApp();

/* one at a time */
// with special "?stimulus-controller" query param, fetch mode and controller id are found
import MyCustomCropper from "./where-we-want/MyCustomCropper?stimulus-controller";
registerController(app, MyCustomCropper);

/* one at a time */
// with special "?stimulus-controller" query param, fetch mode is found
// controller id is deducted from "cropper_controller.ts" filename
import MyCustomCropper from "./assets/controllers/cropper_controller.ts?stimulus-controller";
registerController(app, MyCustomCropper);

// If you don't want all this, you can of course do it basically.
// on the other hand there is no management of lazy behavior
import MyCustomCropper from "./controllers/MyCustomCropper";
app.register("cropper", MyCustomCropper);

// a mix of all of this
registerControllers(
  app,
  import.meta.glob("./where-you-want/*Controller.ts", { query: "?stimulus-controller" })
);

// or
registerControllers(
  app,
  import.meta.glob("./where-you-want/*_controller.ts", { query: "?stimulus-controller" })
);
```

I would like to have your feedback on these proposals.
Does the `stimulusControllerId` option seems interesting to you?

If so, what names should you choose for
- /* stimulusControllerId: 'xxx' */ comment name
- `?stimulus-controller` query parameter

If you have any other ideas or suggestions, please do not hesitate.

one last thing. if we do not keep the option: `stimulusControllerId` but only `stimulusFetch`. there would be an even cleaner way

```ts
import { Controller } from "@hotwired/stimulus";

export const stimulusFetch = 'lazy';

export default class extends Controller {
  // ...
}

```

unfortunately I haven't found a way to implement this if we keep `stimulusControllerId`

**Comment by lhapaipai** [comment]
by the way when you were writing this code

```ts
registerControllers(
app,
// @ts-expect-error - controllers are lazy loaded
transformImportsToLazy(import.meta.glob('./controllers/**/*_(lazy)?controller.[jt]s(x)?'), [
// This controller should not be lazy-loaded afterall, so we do not convert its name
'./controllers/x_controller.ts',
]),
);
```

you could simplify it with this

```ts
registerControllers(
  app,
  // @ts-expect-error - controllers are lazy loaded
  transformImportsToLazy(import.meta.glob('./controllers/**/*_lazycontroller.[jt]s(x)?'))
);
```

**Comment by YummYume** [comment]
Hi @lhapaipai 

The `import.meta` syntax seems like an amazing idea to fix all these problems ! :+1:  I didn't know this was possible for each file. What would `stimulusEnabled` do then ? It would also be great to have in the plugin's options a preferred default value for `stimulusFetch`. In my experience, we sometimes have a lot of controllers that need to be eagerly loaded as soon as possible, but most of the time we only have one or two controllers that need to be eagerly loaded, the rest can just be lazy.

```ts
export default defineConfig(() => ({
  plugins: [
    symfonyPlugin({
      // ...
      stimulus: {
        // ...
        defaultFetch: 'lazy', // 'eager' or 'lazy'
      },
    }),
  ],
});
```

About the `?stimulus` query, we would have to add it to each import then ? I think it's perfectly fine as it allows differentiating which imports are affected by the plugin, much like the esbuild Stimulus plugin (or the [Bun plugin for Stimulus I made](https://github.com/YummYume/bun-stimulus-plugin)).

The only drawback would be that `import.meta.glob` would now require `query` to be set to `?stimulus` and `eager` to be always `true`. Should another method be made to simplify this process as well ? Or maybe a class (like `App`) that would contain all these helpers would be a good idea too. I'm not sure. The types look good to me !

**Comment by lhapaipai** [comment]
I @YummYume
I just finished the doc so you can have the answer to your questions about `import.meta` and the suffix `?stimulus` here : 
https://66c45d9da05dbfdb31712665--cosmic-bubblegum-aa631a.netlify.app/stimulus/reference.html

What still doesn't suit me is the variable name `import.meta.stimulusControllerIdentifier` which I find much too long.

- there is the name `identifier` that we find in the type declaration of Stimulus
```ts
register(identifier: string, controllerConstructor: ControllerConstructor): void;
```
- Symfony has defined the property `name` in its `controllers.json` file.

- `id` is shorter, it still makes a different term.

so I hesitate between `import.meta.stimulusControllerXXX` with XXX as `id` `identifier` `name`.

all your advice is good to take..

very good idea to be able to configure the default value of `stimulusFetch`.

I haven't specified it yet in the doc but the suffix `?stimulus` is not mandatory. If it is omitted the `import.meta` of the files are not taken into account and I made it so that the behavior ("eager" or "lazy") is modeled this time on `import.meta.glob("...", { eager: ??? })`.
I don't think I'll explain it in the doc because it's another less flexible way to achieve the same result and can add confusion, to be seen.

```ts
// lazy controllers
// identifiers generated from file name
registerControllers(
  app,
  import.meta.glob<StimulusControllerInfosImport>(
    "./controllers/*_controller.ts",
  ),
);

// eager controllers
// identifiers generated from file name
registerControllers(
  app,
  import.meta.glob<StimulusControllerInfosImport>(
    "./controllers/*_controller.ts",
    {
      eager: true,
    },
  ),
);
```

**Comment by YummYume** [comment]
Seems all good to me @lhapaipai !

So if you omit `?stimulus`, then it simply won't use the `meta` declarations from the file ?

Also, to me, `identifier` sounds like the best term to use. So I'd go with `import.meta.stimulusIdentifier`, but that's up for debate.

**Comment by lhapaipai** [comment]
hi @YummYume,

> So if you omit ?stimulus, then it simply won't use the meta declarations from the file ?

exactly !

I followed your advice and I am happy to announce that version 7 has been released with all the features we talked about...

lastly I've added 2 vite plugin options:
- `fetchMode` for the default fetch mode
- `identifierResolutionMethod`

v7 integrates some breaking changes with v6 so take the time to look at the doc on [migration](https://symfony-vite.pentatrion.com/extra/migration.html) to update the recipe, etc...

Have a good day
feel free to close this issue if all is ok !

**Comment by YummYume** [comment]
Awesome @lhapaipai ! It all seems very good. I'll update all our Vite projects to the new version once I'm back to work and will let you know if I encounter anything.

By the way, a quick question : if I have a Stimulus controller in a bundle that has a `import.meta.stimulusFetch = 'lazy';` statement, but I need this controller in a specific project to **not** be lazy loaded, what's the best approach to do this ?

- Import it individually (without `?stimulus`) after importing all the controllers from this bundle and register it again
- Import it from the `controllers.json` file
- Create a new controller that extends from it but isn't lazy loaded

What do you think ?

**Comment by lhapaipai** [comment]
My answer is personal and does not take into account the constraints of your project, so you can very well not follow it and be satisfied.

> - Import it individually (without ?stimulus) after importing all the controllers from this bundle and register it again

this will work, but it bothers me because you are referencing a controller where you explicitly wrote that you wanted `lazy` behavior. and you will do a conventional import that could make it look like an error. however a good comment will clear the doubt when other people come back to the code later

> - Import it from the controllers.json file

this doesn't work because at the moment you have to reference third party packages (which contain a reference to the controllers they make available via a `symfony` property in their `package.json`.
[bridge.ts (source code)](https://github.com/lhapaipai/vite-plugin-symfony/blob/03f4587545b874677c7607a0acdf21de5ca0c385/src/stimulus/node/bridge.ts#L24)
this may change over time.

> - Create a new controller that extends from it but isn't lazy loaded

it seems good to me but maybe the other way around

I think I would create the eager version and create a second controller that extends the first and contains `import.meta.stimulusFetch = 'lazy';`

**Comment by YummYume** [comment]
Hi @lhapaipai 

Thanks for clarifying things ! The manual section of the docs is very useful, and I think it's the right approach to that. It's still a very rare occurrence, but it sometimes does happen, that some generic controllers shared across projects sometimes need to be eagerly loaded.

I think with this we can close this issue as it resolves most of the problems present with the previous version :+1:
